#!/usr/bin/env bash
# Script in bash to display numbers 1 to 100
# displays FizzBuzz when the number is a multiple of 3 and 5
# displays Fizz when the number is a multiple of 3
# displays Buzz when the number is a multiple of 5

for ((i=1;i<=100;i++))
do
	if ! ((i%15))
	then
	    echo FizzBuzz
	elif ! ((i%3))
	then
	    echo Fizz
	elif ! ((i%5))
	then
	    echo Buzz
	else
	    echo $i
	fi
done
