#!/usr/bin/env bash
# A bash script displaying numbers and interspersing messages about bad luck superstitions in different countries 

i=1
while [ $i -le 20 ]
do
echo "$i"
case $i in 
4) echo "bad luck from China"
;;
9) echo "bad luck from Japan"
;;
17) echo "bad luck from Italy"
;;
esac
((i++))
done
