#!/usr/bin/env bash
# script in bash to display time of 12:59 

h=0
m=1
while [ $h -le 12 ]; do
	printf "%s\n" "Hour: $h" 
while [ $m -le 59 ]; do
		printf "%s\n" "$m"
	((m+=1))
done
((m = 1))
((h += 1))
done
